version: '2'

services:
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    volumes:
      - ./mysql_data/db:/var/lib/mysql
      - ./data.sql:/tmp/data.sql
      - ./mysqld_ini:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    expose:
      - "3306"
    ports:
      - "3306:3306"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_USERNAME: "dbuser"
      DB_PASSWORD: "dbpass"
      DB_HOST: "db"
    links:
      - "db"
    volumes:
      - ./:/app/web
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
