version: "2"

services:
  mongodb404:
    image: mongo:4.0.4
    container_name: "mongodb404"
    #restart: unless-stopped
    environment:
      - MONGO_DATA_DIR=/Users/youraccount/mongo/404/data
      - MONGO_LOG_DIR=/Users/youraccount/mongo/404/logs
      - MONGO_DATABASE=db
    volumes:
      - ./mongo/404/data:/Users/youraccount/mongo/404/data
    ports:
      - 27018:27017

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: web
    container_name: web
    restart: always
    environment:
      - MONGO_HOSTNAME=mongodb404
      - MONGO_DB=db
      - DB_USERNAME=""
      - DB_PASSWORD=""
    links:
      - "mongodb404"
    volumes:
      - ./:/app
    ports:
      - "80:88"
    depends_on:
      - mongodb404
